# Generated by Django 3.2 on 2024-12-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='file',
            name='output_summary',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='file',
            name='output_translated',
            field=models.CharField(max_length=10000),
        ),
    ]
